### PR TITLE
feat: update markupsafe

### PR DESCRIPTION
**Pull request by dodumosu**
this resolves nditech/apollo-issues#73 by updating markupsafe to 1.1.1

see: nditech/apollo-issues#73

### CODE REVIEW

**Review by takinbo — COMMENTED** [review]
@dodumosu any reason why the requirements generation removed the comments?

**Comment by dodumosu** [comment]
probably due to my version of `pip-tools`. on review, i noticed that the lines that were stripped were all containing "via prod.in". the other comments were left in (for example, backports.csv being added due to the tablib dependency).

**Comment by takinbo** [comment]
I'll have to go through each of those lines to check if the hashes don't differ. Is there an option to add the comments back?

**Review by takinbo — APPROVED** [review]
utACK

**Pull request merged**
